feedback/urls.py
from django.contrib import admin
from django.urls import path
from .views import testi

app_name = 'feedback'
urlpatterns = [
    path('<id>',testi, name ='Testimoni'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('<id>',views.order, name = 'order'),
    path('<id>/<id_order>',views.laundry, name = 'laundry')
]

tugas_ppw_kel_lulus_a/urls.py
from django.contrib import admin
from django.urls import path, include
# from . import views
# from django.conf import settings
# from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
    path('', include('dataPelanggan.urls')),
    path('laundryadmin/', include('laundryadmin.urls')),
    path('feedback/', include('feedback.urls')),
    path('status/', include('status.urls')),
]

feedback/models.py
from django.db import models

# Create your models here.
class Feedback(models.Model):

    Comment = models.CharField(max_length=50)
    bintang= models.IntegerField(default=0)
    date= models.DateTimeField(auto_now=True)
    nama=models.CharField(max_length=20, default= "Rafa")
def __str__(self):
        return self.Comment

feedback/forms.py
from django import forms
from .models import Feedback

class CommentForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['Comment', 'bintang']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
             })

feedback/views.py
from django.shortcuts import render, redirect
# from django.http import HttpResponse
from .models import Feedback
from dataPelanggan.models import dataPelanggan
from . import forms

def testi(request,id):
    if request.method == 'POST':
        pelanggan = dataPelanggan.objects.get(id = id).name
        form = forms.CommentForm(request.POST)
        if form.is_valid():
            testi = form.save()
            testi.nama = pelanggan
            testi.save()
        return redirect('feedback:Testimoni',id)
    else:
        form = forms.CommentForm()
        return render(request, 'Feedback.html', {'form': form, 'list_testimoni' : Feedback.objects.all(), 'id_pelanggan' : id})

feedback/templates/Feedback.html
{% extends "navbar_user.html" %}
{% load static from staticfiles %}

{% block content %}

    <style type="text/css">
    .rat{
            width:93%;
            max-width: 350px;
            text-align: center;
            margin: 4% auto;
            padding: 40px 0;
            border-radius: 5px;
            overflow:hidden ;
            margin-bottom: 25px;
        }
        div.stars{
            width: 270px;
            display:inline-block;
        }
        input.star{
            display: none;
        }
        label.star{
            float: right;
            padding: 10px;
            font-size: 36px;
            color: #444;
            transition:  all 0.2s;
        }
        input.star:checked ~ label.star:before{
            content: '\f005';
            color: #fd4;
            transition: all 0.2s;
        }
        input.star-5:checked ~ label.star:before{
            color: #fe7;
            text-shadow: 0 0 20px #952;
        }
        label.star:before{
            content:'\f006' ;
            font-family:  fontAwesome;
        }
        input.star-1:checked ~label.star:before{
            color: #ff6622;
        }
        .bg-light{
            background-color: transparent !important;
        }
    body{
        height: 100%;
        margin: 0;
    }
    </style>
<div style="background: #AAB4D2;width: 100%;">
      <div class="rat">
    <p>HOW WAS THE SERVICE?</p>
    <div class="stars">
        <form action="">
            <input type="radio" class="star star-5" id="star-5"onclick="bintang5()" name="star">
            <label for="star-5" class="star star-5"></label>

            <input type="radio" class="star star-5" id="star-4" onclick="bintang4()" name="star">
            <label for="star-4" class="star star-5"></label>

            <input type="radio" class="star star-5" id="star-3" onclick="bintang3()"name="star">
            <label for="star-3" class="star star-5"></label>

            <input type="radio" class="star star-5" id="star-2" onclick="bintang2()" name="star">
            <label for="star-2" class="star star-5"></label>

            <input type="radio" class="star star-5" id="star-1" onclick="bintang1()" name="star">
            <label for="star-1" class="star star-5"></label>

        </form>
    </div>
</div>
      <div class="container" style="font-family: 'Chaparral Pro', cursive;">
        <hr style="margin-top: 1%;" />
        <hr />
        <form action="" method="post">
          {% csrf_token %}
          <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-10">
                <label for="id_Comment">Comment:</label>
                <br />
                {{form.Comment}}
                <div style="display: none;">
                <label for="id_bintang">bintang</label>
                <br />
                {{form.bintang}}
                </div>  
            </div>
          </div>
          <div class="form-row">
            <div class="col-sm-1"></div>
            <input
              class="btn"
              type="submit"
              value="SUBMIT"
              name="tombol"
              style="margin-top:3%; background:#D7E0F9; color:black"
            />
          </div>
                <br>
                {% for hasil in list_testimoni %} <br>
                <a>{{hasil.date}}</a>  <br>
                <a>{{hasil.nama}}</a>  <br>
                <a><p>-rate:{{hasil.bintang}}</p></a>
                <a><p>"{{hasil.Comment}} "</p></a>
                {%endfor %}
        </form>
      </div>
    </div>
      {% endblock %}