dataPelanggan/urls.py
from django.urls import path
from . import views

#url for app

app_name = 'dataPelanggan'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('show/<id>',views.show,name='show')
]

feedback/urls.py
from django.contrib import admin
from django.urls import path
from .views import testi

app_name = 'feedback'
urlpatterns = [
    path('<id>',testi, name ='Testimoni'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('<id>',views.order, name = 'order'),
    path('<id>/<id_order>',views.laundry, name = 'laundry')
]

status/urls.py
from django.urls import path
from . import views

app_name = 'status'
urlpatterns = [
    path('<id>',views.status, name = 'status'),
    # path('<id>',views.laundry, name = 'laundry')
    # path('tambahPilihan/',tambahPilihan, name ="tambahPilihan")
]

tugas_ppw_kel_lulus_a/urls.py
from django.contrib import admin
from django.urls import path, include
# from . import views
# from django.conf import settings
# from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
    path('', include('dataPelanggan.urls')),
    path('laundryadmin/', include('laundryadmin.urls')),
    path('feedback/', include('feedback.urls')),
    path('status/', include('status.urls')),
]

dataPelanggan/models.py
from django.db import models

# Create your models here.
class dataPelanggan(models.Model):
    name = models.CharField(max_length =30)
    address = models.CharField(max_length=50)
    number = models.IntegerField()

dataPelanggan/forms.py
from django.db import models
from django import forms
from .models import dataPelanggan


class formPelanggan(forms.ModelForm):
    name = forms.CharField(widget = forms.TextInput(
        attrs = {
            "placeholder" : "Your Name"
        }
    ))

    address = forms.CharField(widget = forms.TextInput(
        attrs = {
            "placeholder" : "Address"
        }
    ))
    number = forms.IntegerField(widget = forms.TextInput(
        attrs = {
            "placeholder" : "Your Number"
        } 
    ))

    class Meta:
        model = dataPelanggan
        fields = ("name","address","number")
        labels = {
            "name" : "namaPelanggan",
            "address" : "alamatPelanggan",
            "number" : "nomorHpPelanggan"
        }

dataPelanggan/views.py
from django.shortcuts import render, redirect
from .models import dataPelanggan
from .forms import formPelanggan
from django.contrib import messages

# Create your views here.
def homepage(request):
    if request.method == "POST":       
        form = formPelanggan(request.POST)
        if form.is_valid():
            pelanggan = form.save()
            return redirect("dataPelanggan:show", pelanggan.id)
        else:
            messages.warning(request, 'Data input is not valid, Please try again!')
            return render(request, 'Homepage.html', {'homepage': form})
    else:
        form = formPelanggan()
        return render(request, 'Homepage.html', {'homepage': form, "navbar" : False })

def show(request, id):
    pelanggan = dataPelanggan.objects.get(id = id)
    nama = pelanggan.name
    return render(request,'Show.html',{'name' : nama, "navbar" : True, "id_pelanggan" : id})

dataPelanggan/templates/Homepage.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class ="containerAtas">
            <h1> We offer you The Best Laundry Service.
                Save time, enjoy your time
            </h1>
            
            <img class="photos" src="https://files.catbox.moe/0f9bdn.jpg">
</div>
<div class = "containerBawah">
            <form method="POST" : action="{% url 'dataPelanggan:homepage' %}" >
                    {% csrf_token %}
                    <table>
                        <tr>
                            {{ homepage.as_table }}
                        </tr>
                    </table>
                        <button class="button" type="submit">Submit</button>       
            </form>

                    {% if messages %}
                        <ul class="messages">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                        </ul>
                    {% endif %}

            <h2>  About Me</h2>
            <h3>
             Our Laundry Service is a convenient and affordable 
            of sending out your loundry to be done by proffesional.
            </h3>
        
</div>
{% endblock %}

dataPelanggan/templates/Show.html
{% extends "base.html" %}
{% load static %}
{% block content %}
        <div class="Regist">
            <h2>Hi {{name}} !</h2>
            <h3>
                Selamat! Anda telah berhasil melakukan registrasi!
                Selanjutnya anda bisa melakukan pemesanan.
            </h3>
        </div>
{% endblock %}

dataPelanggan/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<!--head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> Laundry</title>
    <link rel ="stylesheet" href="{% static 'dataPelanggan/css/homepage.css' %}">
    <link rel = "stylesheet" href = "{% static 'dataPelanggan/css/bootstrap.css' %}">
    </head-->
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
        <link rel="stylesheet" type="text/css" href = "{% static 'dataPelanggan/css/homepage.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Lora|Roboto&display=swap" rel="stylesheet">
    
    </head>
<body style="background-color: #AAB4D2;"><script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>>
    {% include "navbar.html" %}
    {% block content %}
    {% endblock %}
    
    <!--script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" 
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" 
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src = "{% static 'dataPelanggan/js/bundle.min.js' %}"></script-->
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="{% static 'Order.js' %}"></script>

</html>

dataPelanggan/templates/navbar.html
{% load static %}
<!--nav class = "navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand brand" href="#"><b><i>MyLaundry</i></b></a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class = "collapse navbar-collapse" id = "navbarMenu">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0"></ul>
        <form class="form-inline my-2 my-lg-0">
          <a class="nav-link" href="{% url 'dataPelanggan:homepage' %}">Home</a>
          <a class="nav-link" href="#">Order</a>
          <a class="nav-link" href="#">Status</a>
          <a class="nav-link" href="#">Testimoni</a>
        </form>
    </div>
</nav-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top navbar-user" style="padding: .7rem 1rem;">
        <a class="navbar-brand brand" href="#"><b><i>MyLaundry</i></b></a>

        {% if navbar == True %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse topnav"  id="navbarResponsive">
                <ul class="navbar-nav mr-auto w-100 d-flex justify-content-end" style="letter-spacing: 2px;">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'dataPelanggan:homepage' %}">Beranda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'status:status' id=id_pelanggan %}">Status</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'order:order' id=id_pelanggan %}">Pemesanan</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'feedback:Testimoni' id=id_pelanggan %}">Testimoni</a>
                    </li>
                </ul>
            </div>
        {% endif %}
    </nav>