laundryadmin/urls.py
from django.urls import path
from . import views

app_name = 'laundryadmin'
urlpatterns = [
    path('',views.admin, name = 'admin'),
    path('terima/<id>/',views.accept_order, name = 'accept'),
    path('selesai/<id>/', views.finish_order, name = 'finish'),
    path('tolak/<id>/', views.cancel_order, name = 'cancel'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('<id>',views.order, name = 'order'),
    path('<id>/<id_order>',views.laundry, name = 'laundry')
]

tugas_ppw_kel_lulus_a/urls.py
from django.contrib import admin
from django.urls import path, include
# from . import views
# from django.conf import settings
# from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
    path('', include('dataPelanggan.urls')),
    path('laundryadmin/', include('laundryadmin.urls')),
    path('feedback/', include('feedback.urls')),
    path('status/', include('status.urls')),
]

laundryadmin/models.py
from django.db import models

# Create your models here.

laundryadmin/views.py
from django.shortcuts import render, redirect
from order.models import Order, Laundry

# Create your views here.
def admin(request):
    Order.objects.filter(total_harga = 0).delete()
    Laundry.objects.filter(harga_laundry = 0).delete()
    order_complete = Order.objects.filter(status = "Pesanan Selesai")
    total_pendapatan = 0
    for order in order_complete:
        total_pendapatan += order.total_harga
    order_not_complete = Order.objects.exclude(status = "Pesanan Selesai").exclude(status = "Ditolak")
    content = {"order_no" : order_not_complete, "order_yes": order_complete, "pendapatan":total_pendapatan}
    return render(request, "laundryadmin/admin.html", content)

def accept_order(request, id):
    order = Order.objects.get(id = id)
    order.status = "Pesanan Diproses"
    order.save()
    return redirect("laundryadmin:admin")

def finish_order(request, id):
    order = Order.objects.get(id = id)
    order.status = "Pesanan Selesai"
    order.save()
    return redirect("laundryadmin:admin")

def cancel_order(request, id):
    order = Order.objects.get(id = id)
    order.status = "Ditolak"
    order.save()
    return redirect("laundryadmin:admin")

laundryadmin/templates/laundryadmin/admin.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel = 'stylesheet' href = "{% static 'laundryadmin.css' %}">
    <link rel = 'stylesheet' href = "{% static 'navbar.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Laundry Admin</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top navbar-user">
        <a class="navbar-brand brand" href="#"><b><i>MyLaundry</i></b></a>
    </nav>
    <div class = "admin-hlmn" style="padding-top: 100px; padding-bottom: 100px;">
        <div class = "kotak-pendapatan ml-4">
            <p>Gross Income :</p>
            <p>Rp{{pendapatan}}</p>
        </div>
        <div class="bagian-status mt-4">
            <div style="display: flex; flex-direction: column;">
                <h4 style="text-align: center;">Pesanan Pending</h4>
                <div class="kotak-status">
                    {% for order in order_no %}
                    <div class="status">
                    <p>Nama: {{order.nama_pengorder}}</p>
                    <p>Alamat: {{order.alamat}}</p>
                    <p>Nomor Telepon: {{order.nomor_telepon}} </p>
                    <p>Paket: {{order.nama_paket}}</p>
                    {% if order.category == "ambil_sendiri"  %}
                    <p>Drop/Pickup : Pickup</p>
                    {% else %}
                    <p>Drop/Pickup : Drop</p>
                    {% endif %}
                    <p>Total Harga: Rp{{order.total_harga}}</p>
                    <p>Status: {{order.status}}</p>
                    <div class = "laundry-list">
                        {% for laundry in order.laundry.all  %}
                        <div class = "laundry">
                            <p> Berat : {{laundry.berat_paket}} Kg</p>
                            <p> Berat : {{laundry.harga_laundry}}Kg</p>
                        </div>
                        {% endfor %}
                    </div>
                    <div class = "mb-1" style="display: flex; justify-content: space-evenly;">
                        {% if order.status == "Menunggu Verifikasi" %}
                            <a href = "{% url 'laundryadmin:accept' id=order.id  %}">
                                <button value="Accept">Accept</button>
                            </a>
                            <a href = "{% url 'laundryadmin:cancel' id=order.id  %}">
                                <button value="Accept">Cancel</button>
                            </a>
                        {% else %}
                            <a href = "{% url 'laundryadmin:finish' id=order.id  %}">
                                <button value="Accept">Finish</button>
                            </a>
                        {% endif %}
                    </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div>
                <h4 style="text-align: center;">Pesanan Complete</h4>
                <div class="kotak-status">
                   {% for order in order_yes %}
                    <div class="status">
                        <p>Nama: {{order.nama_pengorder}}</p>
                        <p>Alamat: {{order.alamat}}</p>
                        <p>Nomor Telepon: {{order.nomor_telepon}} </p>
                        <p>Paket: {{order.nama_paket}}</p>
                        {% if order.category == "ambil_sendiri"  %}
                        <p>Drop/Pickup : Pickup</p>
                        {% else %}
                        <p>Drop/Pickup : Drop</p>
                        {% endif %}
                        <p>Total Harga: Rp{{order.total_harga}}</p>
                        <p>Status: {{order.status}}</p>
                        <div class = "laundry-list">
                            {% for laundry in order.laundry.all  %}
                            <div class = "laundry">
                                <p> Berat : {{laundry.berat_paket}} Kg</p>
                                <p> Harga : {{laundry.harga_laundry}}Kg</p>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>

    </div>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>